export const navigationItems = [
    { title: 'PO Receiving', route: 'POReceiving', icon: 'cart' },
    { title: 'STO Receiving', route: 'STOReceiving', icon: 'archive' },
    { title: 'Putaway', route: 'Putaway', icon: 'arrow-down' },
    { title: 'Picking', route: 'Picking', icon: 'hand-left' },
    { title: 'WM Stock Inquiry', route: 'WMStockInquiry', icon: 'search' },
    { title: 'IM Stock Inquiry', route: 'IMStockInquiry', icon: 'search' },
    { title: 'EWM Stock Inquiry', route: 'EWMStockInquiry', icon: 'search' },
    { title: 'WM Putaway', route: 'WMPutaway', icon: 'arrow-down' },
    { title: 'WM Picking', route: 'WMPicking', icon: 'hand-left' },
    { title: 'Inventory', route: 'Inventory', icon: 'list' },
    { title: 'Logs', route: 'Logs', icon: 'document-text' },
    { title: 'Offline', route: 'Offline', icon: 'cloud-offline' },
    { title: 'WM Bin to Bin Transfer', route: 'WMBinToBin', icon: 'swap-horizontal' },
    { title: 'IM Inventory', route: 'IMInventory', icon: 'list' },
    { title: 'EWM Putaway', route: 'EWMPutaway', icon: 'arrow-down' },
    { title: 'EWM Picking', route: 'EWMPicking', icon: 'hand-left' },
    { title: 'EWM Bin to Bin Transfer', route: 'EWMBinToBin', icon: 'swap-horizontal' },
    { title: 'IM Reversals', route: 'IMReversals', icon: 'return-up-back' },
    { title: 'IM Transfer', route: 'IMTransfer', icon: 'swap-vertical' },
];
